### ISSUE TITLE
PHP 7 Warning count()

### ISSUE THREAD

**Issue by zonky2** [menatwork-ia/clipboard#23]
```
Warning: count(): Parameter must be an array or an object that implements Countable in composer/vendor/menatwork/clipboard/system/modules/clipboard/classes/ClipboardXml.php on line 174

#0 composer/vendor/menatwork/clipboard/system/modules/clipboard/classes/ClipboardXml.php(174): __error(2, 'count(): Parame...', '/home/www/conta...', 174, Array)
#1 composer/vendor/menatwork/clipboard/system/modules/clipboard/classes/ClipboardXml.php(203): ClipboardXml->hasElements()
#2 composer/vendor/menatwork/clipboard/system/modules/clipboard/classes/ClipboardXml.php(188): ClipboardXml->getFavorite()
#3 system/modules/clipboard/dca/tl_page.php(54): ClipboardXml->hasFavorite()
#4 system/modules/core/library/Contao/DcaLoader.php(91): include('/home/www/conta...')
#5 system/modules/core/library/Contao/Controller.php(1319): Contao\DcaLoader->load(false)
#6 system/modules/core/classes/Backend.php(376): Contao\Controller::loadDataContainer('tl_page')
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('page')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}
```

**Comment by mandrael** [comment]
You can temporarily deactivate modules and switch source and target site to PHP 5.6. I had no issues then, except all images were missing in the target (because of the use of insert tags, which didn't work).
